### ISSUE TITLE
No regex verification for License fields when getting a trial

### ISSUE THREAD

**Issue by msmeria** [xwikisas/xwiki-pro#14]
I was able to get a trial for XWiki Pro using only 1 space (" ") for all required fields: FIRST NAME, LAST NAME and EMAIL.

We should check the name fields for letters (at least 2 or 3) and the email field for the email format.

**Comment by acotiuga** [comment]
This is a license application issue. Moving it there: https://github.com/xwikisas/application-licensing/issues/43.
